backend:
  name: github
  repo: thangchiba/ThangChibaBlog
  branch: main

media_folder: "public/static/images"  # The folder where uploaded media will be stored
public_folder: "/images"  # The public URL path to access the media
collections:
  - name: "english_posts"
    label: "English Posts"
    folder: "BlogFE/data/en/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "mdx"
    format: "frontmatter"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Draft", name: "draft", widget: "boolean" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Audio URL", name: "audioURL", widget: "string" }
      - { label: "Authors", name: "authors", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
